sudo: false
language: php

php:
  - hhvm
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script:
  - composer install || sleep 60 && composer install
  - mysql -e 'create database aimeos;'
  - echo "<?php return array( 'db' => array( 'adapter' => 'mysql', 'host' => '127.0.0.1', 'database' => 'aimeos', 'username' => 'root', 'password' => '', 'limit' => 2, 'opt-persistent' => false, 'stmt' => array( \"SET NAMES 'utf8'\", \"SET SESSION sql_mode='ANSI'\" ) ) );" > config/resource.php
  - echo "<?php return array( 'db' => array( 'adapter' => 'mysql', 'host' => '127.0.0.1', 'database' => 'aimeos', 'username' => 'root', 'password' => '', 'limit' => 2, 'opt-persistent' => false, 'stmt' => array( \"SET NAMES 'utf8'\", \"SET SESSION sql_mode='ANSI'\" ) ) );" > lib/mwlib/tests/config/resource.php

script: "vendor/bin/phing setup coverage check"

after_success:
  - php vendor/bin/coveralls

matrix:
  fast_finish: true
