sudo: true
language: php

addons:
  apt:
    packages:
    - php5-pgsql

php:
  - hhvm
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

env:
  - DB=mysql

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: DB=pgsql

before_install:
  - sudo /etc/init.d/postgresql stop
  - curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install postgresql postgresql-contrib
  - sudo /etc/init.d/postgresql start

before_script:
  - composer self-update
  - composer install || sleep 60 && composer install
  - if [[ $DB = 'mysql' ]]; then mysql -e "CREATE DATABASE aimeos;"; fi
  - if [[ $DB = 'mysql' ]]; then echo "<?php return array( 'db' => array( 'adapter' => 'mysql', 'host' => '127.0.0.1', 'database' => 'aimeos', 'username' => 'root', 'password' => '', 'limit' => 2, 'opt-persistent' => false, 'stmt' => array( \"SET NAMES 'utf8'\", \"SET SESSION sql_mode='ANSI'\" ) ), 'fs' => array( 'adapter' => 'Standard', 'basedir' => '.' ), 'mq' => array( 'adapter' => 'Standard', 'db' => 'db' ) );" > config/resource.php; fi
  - if [[ $DB = 'pgsql' ]]; then sudo -u postgres psql -c "CREATE DATABASE aimeos;" -p 5433 postgres; fi
  - if [[ $DB = 'pgsql' ]]; then sudo -u postgres psql -c "CREATE USER aimeos PASSWORD 'aimeos';" -p 5433 postgres; fi
  - if [[ $DB = 'pgsql' ]]; then sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE aimeos TO aimeos;" -p 5433 postgres; fi
  - if [[ $DB = 'pgsql' ]]; then echo "<?php return array( 'db' => array( 'adapter' => 'pgsql', 'host' => '127.0.0.1', 'port' => 5433, 'database' => 'aimeos', 'username' => 'aimeos', 'password' => 'aimeos', 'limit' => 2, 'opt-persistent' => false, 'stmt' => array() ), 'fs' => array( 'adapter' => 'Standard', 'basedir' => '.' ), 'mq' => array( 'adapter' => 'Standard', 'db' => 'db' ) );" > config/resource.php; fi

script: "vendor/bin/phing setup coverage check"

after_success:
  - php vendor/bin/coveralls
